services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        target: dev
    environment:
      ETCD_CLIENT_URL: http://etcd:2379
    ports:
      - "8585:8585"
    volumes:
      - ./:/app:delegated
    depends_on:
      etcd:
        condition: service_healthy

  etcd:
    container_name: etcd
    image: bitnami/etcd:3.5.9
    restart: always
    ports:
     - "12379:2379"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - LISTEN_CLIENT_URLS=http://etcd:2379
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/etcd/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
