# https://taskfile.dev

version: "3"

tasks:
  proto_lint:
    cmds:
      - buf lint ./protobuf

  proto_gen:
    cmds:
      - |
        cd ./protobuf
        buf generate

  grpc_list:
    cmds:
      - grpcurl -plaintext localhost:8585 list

  grpc_target:
    cmds:
      - grpcurl -plaintext localhost:8585 list something.v1.Service

  # grpc_update:
  #   cmds:
  #     - grpcurl -plaintext -d '{"value": "yes"}' localhost:8585 something.v1.Service.Update

  grpc_get:
    cmds:
      - grpcurl -plaintext localhost:8585 something.v1.Service.Check
